config/routes.rb
Rails.application.routes.draw do
  resources :searches

  resources :incidents

  resources :incident_categories

  resources :responsibles

  root 'incidents#index'

end

app/models/incident_category.rb
class IncidentCategory < ActiveRecord::Base
	has_many :incidents, dependent: :destroy, inverse_of: :incident_category
	validates :name, presence: true, uniqueness: true, length: { minimum: 3 }
end

app/controllers/incident_categories_controller.rb
class IncidentCategoriesController < ApplicationController
  before_action :set_incident_category, only: [:show, :edit, :update, :destroy]

  # GET /incident_categories
  # GET /incident_categories.json
  def index
    @incident_categories = IncidentCategory.all
  end

  # GET /incident_categories/1
  # GET /incident_categories/1.json
  def show
  end

  # GET /incident_categories/new
  def new
    @incident_category = IncidentCategory.new
  end

  # GET /incident_categories/1/edit
  def edit
  end

  # POST /incident_categories
  # POST /incident_categories.json
  def create
    @incident_category = IncidentCategory.new(incident_category_params)

    respond_to do |format|
      if @incident_category.save
        format.html { redirect_to @incident_category, notice: 'Tipo de incidente creado.' }
        format.json { render :show, status: :created, location: @incident_category }
      else
        format.html { render :new }
        format.json { render json: @incident_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incident_categories/1
  # PATCH/PUT /incident_categories/1.json
  def update
    respond_to do |format|
      if @incident_category.update(incident_category_params)
        format.html { redirect_to @incident_category, notice: 'Incident category was successfully updated.' }
        format.json { render :show, status: :ok, location: @incident_category }
      else
        format.html { render :edit }
        format.json { render json: @incident_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incident_categories/1
  # DELETE /incident_categories/1.json
  def destroy
    @incident_category.destroy
    respond_to do |format|
      format.html { redirect_to incident_categories_url, notice: 'Incident category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_incident_category
      @incident_category = IncidentCategory.find(params[:id])
    end

    def incident_category_params
      params.require(:incident_category).permit(:name)
    end
end

app/helpers/incident_categories_helper.rb
module IncidentCategoriesHelper
end

app/views/incident_categories/_form.html.erb
<%= form_for(@incident_category) do |f| %>
  <% if @incident_category.errors.any? %>
    <div class="alert alert-danger">
      <h4>Error:</h4>
      <ul>
      <% @incident_category.errors.each do |field, message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
  <div class="form-group col-lg-6">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  </div>
  <div class="row">
  <div class="form-group col-lg-6">
    <%= f.submit 'Save category', :class => 'btn btn-primary' %>
  </div>
  </div>
<% end %>

app/views/incident_categories/edit.html.erb
<h1>Edit Issue Category</h1>

<%= render 'form' %>

<%= link_to 'Ver versión actual', @incident_category %>

app/views/incident_categories/index.html.erb
<h1>Issue Categories</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr class="info">
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @incident_categories.each do |incident_category| %>
      <tr>
        <td><%= link_to incident_category.name, incident_category %></td>
        <td><%= link_to '<i class="fa fa-pencil-square-o fa-lg"></i>'.html_safe, edit_incident_category_path(incident_category) %></td>
        <td><%= link_to '<i class="fa fa-trash fa-lg"></i>'.html_safe, incident_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div >
<h4>
  <%= link_to 'Add new issue category', new_incident_category_path %>
</h4>

</div>

app/views/incident_categories/new.html.erb
<h1>New Issue Category</h1>

<%= render 'form' %>

app/views/incident_categories/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <strong>Issue Category</strong>
  <%= @incident_category.name %>
</h3>
<div class="list-group">
<div  class="list-group-item active">
<strong>Issues in this Category</strong>
</div>

	<%= render @incident_category.incidents %>

</div>


<%= link_to 'Editar tipo de incidente', edit_incident_category_path(@incident_category) %>