config/routes.rb
Rails.application.routes.draw do
  resources :searches

  resources :incidents

  resources :incident_categories

  resources :responsibles

  root 'incidents#index'

end

app/views/includes/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/incidents">IssuesApp</a>
  </div>
  <div class="navbar-collapse collapse navbar-inverse-collapse">
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if params[:controller] == 'incidents' %>"><%= link_to "Dashboard", incidents_path %></li>
      <li class="<%= 'active' if params[:controller] == 'responsibles' %>"><%= link_to "Manage Responsibles", responsibles_path %></li>
      <li class="<%= 'active' if params[:controller] == 'incident_categories' %>"><%= link_to "Manage Issue Categories", incident_categories_path %></li>

    </ul>


  </div>
  </div>
</div>

app/views/includes/_sidebar.html.erb
<br>
<br>

<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Dashboard Options</h3>
  </div>
  <div class="panel-body">
  	<%= link_to '<i class="fa fa-plus"></i> Add Issue'.html_safe, new_incident_path, :class => "list-group-item"  %>
    <%= link_to '<i class="fa fa-search"></i> Advanced Search'.html_safe, new_search_path, :class => "list-group-item" %>
  <a href="#view_graphic" class="list-group-item"><i class="fa fa-bar-chart"></i> Show chart
  </a>
  <br>
<br>
<br>
<br>
  </div>
</div>