config/routes.rb
Rails.application.routes.draw do
  resources :searches

  resources :incidents

  resources :incident_categories

  resources :responsibles

  root 'incidents#index'

end

app/models/incident.rb
class Incident < ActiveRecord::Base
  belongs_to :responsible, inverse_of: :incidents
  belongs_to :incident_category, inverse_of: :incidents

  validates :priority, presence: true, numericality: {only_integer: true},
					             inclusion: { in: 1..10 }

  validates :description, presence: true, length: { minimum: 10 }

  validates :name, presence: true, uniqueness: true, length: { minimum: 5 }

  validates :responsible, presence: true

  validates :incident_category, presence: true
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:show, :edit, :update, :destroy]

  # GET /incidents
  # GET /incidents.json
  def index
    @incidents = Incident.all
  end


  # GET /incidents/1
  # GET /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    if !Responsible.exists?
      flash[:error] ||= []
      flash[:error].push("There's no responsibles in the system. Please create one.")
    end
    if !IncidentCategory.exists?
      flash[:error] ||= []
      flash[:error].push("There's no category in the system. Please create one.")
    end
    if flash[:error]
      redirect_to incidents_path
    else
      @incident = Incident.new
    end
  end

  # GET /incidents/1/edit
  def edit
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(incident_params)
    respond_to do |format|
        if @incident.save
          format.html { redirect_to @incident, notice: 'Issue was successfully created' }
          format.json { render :show, status: :created, location: @incident }
       else
          format.html { render :new }
          format.json { render json: @incident.errors, status: :unprocessable_entity }
        end

    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    respond_to do |format|
      if @incident.update(incident_params)
        format.html { redirect_to @incident, notice: 'Issue was successfully updated' }
        format.json { render :show, status: :ok, location: @incident }
      else
        format.html { render :edit }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    respond_to do |format|
      format.html { redirect_to incidents_url, notice: 'Incident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_incident
      @incident = Incident.find(params[:id])
    end

    def incident_params
      params.require(:incident).permit(:name, :description, :priority, :responsible_id, :incident_category_id)
    end
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_form.html.erb
<%= form_for(@incident) do |f| %>
  <% if @incident.errors.any? %>
    <div class="alert alert-danger">
      <h4>Error:</h4>
      <ul>
      <% @incident.errors.each do |field, message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="row">
    <div class="form-group col-lg-6">
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label "Choose the issue category" %><br>

        <%= f.collection_select :incident_category_id, IncidentCategory.order(:name),:id,:name, {include_blank: "None selected"}, {:class => 'form-control'} %>

      </div>
       <div class="field">
        <%= f.label :description %><br>
        <%= f.text_area :description, class: 'form-control' %>
      </div>

      <div class="row">
       <div class="field col-lg-2">
        <%= f.label :priority, 'Priority (1 - 10)' %><br>
        <%= f.number_field :priority, :min=>"1", :max=>"10", class: 'form-control' %>
        </div>
      </div>



      <div class="field">
        <%= f.label "Choose assigned responsible" %><br>

        <%= f.collection_select :responsible_id, Responsible.order(:name),:id,:name, {include_blank: "None selected"}, {:class => 'form-control'} %>

      </div>

    </div>
  </div>
    <div class="row">
      <div class="form-group col-lg-6">
        <%= f.submit 'Save issue',  :class => 'btn btn-primary'%>
      </div>
  </div>


<% end %>

app/views/incidents/_incident.html.erb
<%= link_to incident.name, incident_path(incident), :class=>"list-group-item" %>

app/views/incidents/_incidentsearch.html.erb
 <tr>
  <td><%= link_to incident.name, incident %></td>
  <td><%= link_to incident.responsible.name, controller: "responsibles", action: "show", id: incident.responsible.id %></td>
  <td><%= incident.priority %></td>
  <td><%= link_to incident.incident_category.name, controller: "incident_categories", action: "show", id: incident.incident_category.id %></td>
  <td><%= link_to '<i class="fa fa-pencil-square-o fa-lg"></i>'.html_safe, edit_incident_path(incident)%></td>
  <td><%= link_to '<i class="fa fa-trash fa-lg"></i>'.html_safe, incident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/incidents/edit.html.erb
<h1>Edit Issue</h1>

<%= render 'form' %>

<%= link_to 'See current version', @incident %> 

app/views/incidents/index.html.erb
<div class="row">
<div class="col-lg-3 " style="">
<%= render 'includes/sidebar' %>
</div>


<div class="col-lg-9">
  <% if flash[:error] %>
    <div class="alert alert-warning">
      <% flash[:error].each do |error| %>
        <div>
          <%= error %>
        </div>
      <% end %>
    </div>
  <% end %>
<h1>Issues</h1>

<div class="row">
  <div class="col-lg-4">
    <h4>Quick search</h4>
    <input id="table_search" type="text" placeholder="Write some keywords..." name="" class="form-control">
    </input>
    <br>
  </div>
</div>

<table id="table_incidents" class="tablesorter table table-striped table-hover" data-filter="#table_search" data-filter-minimum="1" data-filter-timeout="150">
  <thead>
    <tr class="info">
      <th>Name</th>
      <th>Responsible</th>
      <th>Priority</th>
      <th>Category</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody id="#table_body">
    <% @incidents.each do |incident| %>
      <tr>
        <td><%= link_to incident.name, incident %></td>
        <!-- Link al responsable -->
        <td><%= link_to incident.responsible.name, controller: "responsibles", action: "show", id: incident.responsible.id %></td>
        <td><%= incident.priority %></td>
        <!-- Link a la categoría -->
        <td><%= link_to incident.incident_category.name, controller: "incident_categories", action: "show", id: incident.incident_category.id %></td>
        <td><%= link_to '<i class="fa fa-pencil-square-o fa-lg"></i>Edit'.html_safe, edit_incident_path(incident)%></td>
        <td><%= link_to '<i class="fa fa-trash fa-lg"></i>Remove'.html_safe, incident, method: :delete, data: { confirm: '¿Está seguro que desea eliminarlo?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>




<div class="row">
  <div class="col-lg-9">
    <hr>
  <h4 id="view_graphic">Chart: Amount of Issues per Category</h4>
  <hr>
<div id='dashboard'>
</div>
</div>
</div>
</div>
</div>
<script type="text/javascript">
var ready;
ready = function() {
        //Se le aplica el jQuery Filterable a la tabla
        $('table').footable();

        //Se le aplica el jQuery tablesorter a la tabla
        $('#table_incidents').tablesorter({sortList: [[2,0]],
           headers: { 4: {
            sorter:false
           }
         }
        } );


        //Se generan los datos para la gráfica con d3
         var freqData=[
            <% @categories = IncidentCategory.all %> <% @categories.each do |category| %> {State:'<%= category.name %>',freq:<%= raw category.incidents.count %>},<% end %>
            ];

        dashboard('#dashboard',freqData);
    }
 //se ejecuta el document ready como también en el page load de Turbolinks
$(document).ready(ready);
$(document).on('page:load', ready);
</script>

app/views/incidents/new.html.erb
<h1>New Issue</h1>

<%= render 'form' %>

app/views/incidents/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <strong>Name:</strong>
  <%= @incident.name %>
</h3>

<h3>
  <strong>Assigned Responsible:</strong>
  <%= link_to @incident.responsible.name, @incident.responsible %>
</h3>

<h3>
  <strong>Category:</strong>
  <%= link_to @incident.incident_category.name, @incident.incident_category %>
</h3>

<div class="well">
<p>
	<h3><strong>Description</strong></h3>
	<hr>
	<%= @incident.description %>
</p>
</div>
<div class="container">
<h5>
<%= link_to '<i class="fa fa-pencil-square-o"></i>Edit Issue'.html_safe, edit_incident_path(@incident) %>
</h5>
<br>
<h5>
<%= link_to '<i class="fa fa-arrow-left"></i>Back to Dashboard'.html_safe, incidents_path  %>
</h5>
</div>