config/routes.rb
Rails.application.routes.draw do
  resources :searches

  resources :incidents

  resources :incident_categories

  resources :responsibles

  root 'incidents#index'

end

app/models/responsible.rb
class Responsible < ActiveRecord::Base
	has_many :incidents, dependent: :destroy, inverse_of: :responsible
	validates :name,  presence: true, uniqueness: true, length: { minimum: 5 }
end

app/controllers/responsibles_controller.rb
class ResponsiblesController < ApplicationController
  before_action :set_responsible, only: [:show, :edit, :update, :destroy]

  #Controlador generado con rails scaffold, y luego editado.


  # GET /responsibles
  # GET /responsibles.json
  def index
    @responsibles = Responsible.all
  end

  # GET /responsibles/1
  # GET /responsibles/1.json
  def show
  end

  # GET /responsibles/new
  def new
    @responsible = Responsible.new
  end

  # GET /responsibles/1/edit
  def edit
  end

  # POST /responsibles
  # POST /responsibles.json
  def create
    @responsible = Responsible.new(responsible_params)

    respond_to do |format|
      if @responsible.save
        format.html { redirect_to @responsible, notice: 'Responsable creado satisfactoriamente' }
        format.json { render :show, status: :created, location: @responsible }
      else
        format.html { render :new }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responsibles/1
  # PATCH/PUT /responsibles/1.json
  def update
    respond_to do |format|
      if @responsible.update(responsible_params)
        format.html { redirect_to @responsible, notice: 'Responsable editado satisfactoriamente' }
        format.json { render :show, status: :ok, location: @responsible }
      else
        format.html { render :edit }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsibles/1
  # DELETE /responsibles/1.json
  def destroy
    @responsible.destroy
    respond_to do |format|
      format.html { redirect_to responsibles_url, notice: 'Responsible was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_responsible
      @responsible = Responsible.find(params[:id])
    end

    def responsible_params
      params.require(:responsible).permit(:name)
    end
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/views/responsibles/_form.html.erb
<%= form_for(@responsible) do |f| %>
  <% if @responsible.errors.any? %>
    <div class="alert alert-danger">
      <h4>Error:</h4>

      <ul>
      <% @responsible.errors.each do |field, message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<fieldset>
  <div class="row">
  <div class="form-group col-lg-6">

    <%= f.label :name, class: 'control-label' %>
    <%= f.text_field :name, class: 'form-control'%>
  </div>
  </div>
  <div class="row">
  <div class="form-group  col-lg-6">
    <%= f.submit 'Save Responsible', :class => 'btn btn-primary' %>
  </div>
  </div>
</fieldset>
<% end %>

app/views/responsibles/edit.html.erb
<h1>Edit Responsible</h1>

<%= render 'form' %>

<%= link_to 'Ver versión actual', @responsible %>

app/views/responsibles/index.html.erb
<h1>Responsibles</h1>

<table class="table table-striped table-hover ">
  <thead>
    <tr class="info">
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @responsibles.each do |responsible| %>
      <tr>
        <td><%= link_to responsible.name, responsible %></td>

        <td><%= link_to '<i class="fa fa-pencil-square-o fa-lg"></i>'.html_safe, edit_responsible_path(responsible) %></td>
        <td><%= link_to '<i class="fa fa-trash fa-lg"></i>'.html_safe, responsible, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <h4>
    <%= link_to 'Add responsible', new_responsible_path %>
  </h4>
</div>

app/views/responsibles/new.html.erb
<h1>New Responsible</h1>

<%= render 'form' %>

<%= link_to 'Back', responsibles_path %>

app/views/responsibles/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
  <strong>Name:</strong>
  <%= @responsible.name %>
</h3>

<div class="list-group">
<div  class="list-group-item active">
<strong>Issues created body <%= @responsible.name %> </strong>
</div>
	<%= render @responsible.incidents %>

</div>
<%= link_to 'Edit Responsible', edit_responsible_path(@responsible) %> 